CURSOS_2020 = iter([
    ['Apodi', 'Agropecuária', 'Matutino', 36],
    ['Apodi', 'Agropecuária', 'Vespertino', 36],
    ['Apodi', 'Informatica', 'Vespertino', 36],
    ['Apodi', 'Química', 'Matutino', 40],
    ['Caico', 'Eletrotécnica', 'Vespertino', 40],
    ['Caico', 'Informática para Internet', 'Vespertino', 80],
    ['Caico', 'Têxtil', 'Vespertino', 40],
    ['Caico', 'Vestuário', 'Vespertino', 40],
    ['Canguaretama', 'Eletromecânica', 'Vespertino', 40],
    ['Canguaretama', 'Eventos', 'Vespertino', 40],
    ['Canguaretama', 'Informática', 'Vespertino', 40],
    ['Ceará-Mirim', 'Equipamentos Biomédicos', 'Vespertino', 36], 
    ['Ceará-Mirim', 'Informática', 'Matutino', 36],
    ['Ceará-Mirim', 'Programador de Jogos Digitais', 'Matutino', 36], 
    ['Ceará-Mirim', 'Programador de Jogos Digitais', 'Vespertino', 36], 
    ['Currais Novos', 'Alimentos', 'Vespertino', 40],
    ['Currais Novos', 'Alimentos', 'Matutino', 40],
    ['Currais Novos', 'Informática', 'Matutino', 40],
    ['Currais Novos', 'Manutencao e Suporte em Informatica', 'Vespertino', 40],
    ['Ipanguacu', 'Agroecologia', 'Vespertino', 36],
    ['Ipanguacu', 'Informatica', 'Vespertino', 36],
    ['Ipanguacu', 'Meio Ambiente', 'Matutino', 36],
    ['Joao Camara', 'Administracao', 'Matutino', 40],
    ['Joao Camara', 'Eletrotecnica', 'Matutino', 40],
    ['Joao Camara', 'Informatica', 'Matutino', 40],
    ['Lajes', 'Administracao', 'Vespertino', 72],
    ['Lajes', 'Informatica', 'Matutino', 36],
    ['Macau', 'Informatica', 'Vespertino', 36],
    ['Macau', 'Quimica', 'Matutino', 36],
    ['Macau', 'Recursos', 'Matutino', 36],
    ['Mossoro', 'Edificacoes', 'Matutino', 36],
    ['Mossoro', 'Eletrotecnica', 'Matutino', 36],
    ['Mossoro', 'Informatica', 'Vespertino', 36],
    ['Mossoro', 'Mecanica', 'Vespertino', 36],
    ['Natal - Central', 'Administracao', 'Matutino', 36],
    ['Natal - Central', 'Controle Ambiental', 'Matutino', 40], 
    ['Natal - Central', 'Controle Ambiental', 'Vespertino', 40], 
    ['Natal - Central', 'Edificacoes', 'Matutino', 40], 
    ['Natal - Central', 'Edificacoes', 'Vespertino', 40], 
    ['Natal - Central', 'Eletrotecnica', 'Vespertino', 40],
    ['Natal - Central', 'Geologia', 'Matutino', 40],
    ['Natal - Central', 'Informatica para Internet', 'Matutino', 36],
    ['Natal - Central', 'Manutencao e Suporte em Infomatica', 'Vespertino', 36],
    ['Natal - Central', 'Mecanica', 'Vespertino', 40],
    ['Natal - Central', 'Mineracao', 'Vespertino', 40],
    ['Natal - Cidade Alta', 'Lazer', 'Matutino', 36],
    ['Natal - Cidade Alta', 'Multimidia', 'Matutino', 36], 
    ['Natal - Cidade Alta', 'Multimidia', 'Vespertino', 36], 
    ['Natal - Zona Norte', 'Comercio', 'Vespertino', 36],
    ['Natal - Zona Norte', 'Eletronica', 'Vespertino', 36],
    ['Natal - Zona Norte', 'Eletronica', 'Matutino', 36],
    ['Natal - Zona Norte', 'Informatica para Internet', 'Matutino', 36],
    ['Nova Cruz', 'Administracao', 'Vespertino', 40],
    ['Nova Cruz', 'Informatica', 'Matutino', 40],
    ['Nova Cruz', 'Quimica', 'Vespertino', 40],
    ['Nova Cruz', 'Quimica', 'Matutino', 40],
    ['Parelhas', 'Informatica', 'Matutino', 36],
    ['Parelhas', 'Mineracao', 'Vespertino', 36],
    ['Parelhas', 'Mineracao', 'Vespertino ', 36],
    ['Parnamirim', 'Informatica', 'Matutino', 40], 
    ['Parnamirim', 'Informatica', 'Vespertino', 40], 
    ['Parnamirim', 'Mecatronica', 'Matutino', 40], 
    ['Parnamirim', 'Mecatronica', 'Vespertino', 40], 
    ['Pau Dos Ferros', 'Alimentos', 'Matutino', 36], 
    ['Pau Dos Ferros', 'Alimentos', 'Vespertino', 36], 
    ['Pau Dos Ferros', 'Apicultura', 'Matutino', 36], 
    ['Pau Dos Ferros', 'Apicultura', 'Vespertino', 36], 
    ['Pau Dos Ferros', 'Informatica', 'Matutino', 36], 
    ['Pau Dos Ferros', 'Informatica', 'Vespertino', 36], 
    ['Santa Cruz', 'Informatica', 'Matutino', 36], 
    ['Santa Cruz', 'Informatica', 'Vespertino', 36], 
    ['Santa Cruz', 'Mecanica', 'Vespertino', 36],
    ['Santa Cruz', 'Refrigeracao e Climatizacao', 'Matutino', 36],
    ['Sao Gonçalo do Amarante', 'Edificacoes', 'Matutino', 40], 
    ['Sao Gonçalo do Amarante', 'Edificacoes', 'Vespertino', 40], 
    ['Sao Gonçalo do Amarante', 'Informatica', 'Matutino', 40],
    ['Sao Gonçalo do Amarante', 'Logistica', 'Vespertino', 40],
    ['Sao Paulo Do Potengi', 'Edificacoes', 'Matutino', 36], 
    ['Sao Paulo Do Potengi', 'Edificacoes', 'Vespertino', 36], 
    ['Sao Paulo Do Potengi', 'Informatica para Internet', 'Matutino', 40],
    ['Sao Paulo Do Potengi', 'Meio Ambiente', 'Matutino', 36], 
    ['Sao Paulo Do Potengi', 'Meio Ambiente', 'Vespertino', 36],
])
